# Generated by Django 4.2.5 on 2023-11-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='ratings',
            field=models.ManyToManyField(blank=True, to='core.rating'),
        ),
        migrations.AddField(
            model_name='question',
            name='ratings',
            field=models.ManyToManyField(blank=True, to='core.rating'),
        ),
    ]
